server:
  port: 19945
spring:
  application:
    name: code-learn
  datasource:
    url: jdbc:mysql://localhost:3306/mybaties?useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: zxx1994
    driver-class-name: com.mysql.jdbc.Driver
    type:  com.zaxxer.hikari.HikariDataSource

  redis:
    host: 10.253.254.17
    port: 6379
logging:
  file: logs/log.log
  level.root: warn
  #  pattern:
  #    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %m%n'
  #    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{10} - %m%n'
  level.pri.zxx.webdemo.mappers: warn